services:

  app:
    build:
      context: .
      dockerfile: Dockerfile

    container_name: url-shortener-app

    ports:
      - "3000:3000"

    environment:
      NODE_ENV: development
      PORT: 3000

      DB_HOST: mysql
      DB_PORT: 3306
      DB_NAME: shortener_dev
      DB_USER: root
      DB_PASSWORD: root

    depends_on:
      mysql:
        condition: service_healthy

  mysql:
    image: mysql:8.4

    container_name: url-shortener-mysql

    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: shortener_dev

    ports:
      - "3300:3300"

    volumes:
      - mysql_data:/var/lib/mysql

    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-proot"]
      interval: 5s
      timeout: 5s
      retries: 10

volumes:
  mysql_data:
